<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcLibrary\PlcLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PlcLibrary.Tests" />
  </ItemGroup>

</Project>
