<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcLibrary\PlcLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PlcLibrary.Tests" />
  </ItemGroup>

</Project>
