<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.378.156" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcLibrary\PlcLibrary.csproj" />
  </ItemGroup>

</Project>
