<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <ProjectReference Include="..\PlcLibrary\PlcLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PlcLibrary.Tests" />
  </ItemGroup>

</Project>
